# Generated by Django 4.0.4 on 2022-05-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_note_additional_note_alter_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='meals',
            field=models.JSONField(blank=True),
        ),
    ]
