# Generated by Django 4.0.4 on 2022-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='foodlist',
            field=models.JSONField(blank=True, default='NULL'),
        ),
    ]
