# Generated by Django 4.0.4 on 2022-05-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diary_foodlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='foodlist',
            new_name='mealslist',
        ),
    ]
